repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff
        args: [--select, "I", --fix, --exit-non-zero-on-fix]

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        types_or: [python]

  - repo: local
    hooks:
      - id: shfmt
        name: shfmt
        language: docker_image
        entry: mvdan/shfmt:v3.10.0 -w -i 4
        types: [shell]

      - id: shellcheck
        name: shellcheck
        language: docker_image
        entry: koalaman/shellcheck:v0.10.0 --severity=warning
        types: [shell]
