apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: tpu-7x-multi-host
spec:
  headGroupSpec:
    template:
      spec:
        containers:
        - name: ray-head
          image: rayproject/ray:nightly-py312-tpu
          resources:
            requests:
              cpu: "1"
            limits:
              cpu: "1"
  workerGroupSpecs:
  - replicas: 1
    minReplicas: 1
    maxReplicas: 1
    groupName: tpu-worker-group
    numOfHosts: 2
    template:
      spec:
        containers:
        - name: ray-worker
          image: rayproject/ray:nightly-py312-tpu
          resources:
            requests:
              google.com/tpu: "4"
            limits:
              google.com/tpu: "4"
        nodeSelector:
          cloud.google.com/gke-tpu-accelerator: tpu7x
          cloud.google.com/gke-tpu-topology: 2x2x2
